### ISSUE TITLE
Can't disable a casein_select

### ISSUE THREAD

**Issue by lbain** [spoiledmilk/casein#2]
I'd like to disable a select option in certain conditions. In the past I've successfully used `disabled: true` like this:

```
= casein_text_field f, f.object, :field, disabled: true
```

But the select doesn't seem to work.

```
= casein_select f, f.object, :field, {test: 1}, disabled: true
```

This results in a working select drop down.

Is it possible to disable a `casein_select` field? If so, how should I change my code to work properly?

**Comment by russellquinn** [comment]
This version of Casein is for Rails 2.x. Can you confirm you're still using this one, and not the latest? (github.com/russellquinn/casein)

**Comment by lbain** [comment]
Ops! Sorry, my mistake. I'll move this to the correct repo.
